[package]
name = "cgcollide"
version = "0.1.0"
authors = ["LambdaXymox <lambda.xymox@gmail.com>"]
edition = "2018"
descriptioin = "A collision detection and resolution library for real-time computer graphics."

[dependencies]
